#!/bin/python3

import math
import os
import random
import re
import sys
from collections import Counter


if __name__ == '__main__':
    s = sorted(input())
    #s.sort()
    d = Counter(s)
    for i,j in d.most_common(3):
        print(i,j)